#import pygame_sdl2
#pygame_sdl2.import_as_pygame()

import pygame, os

web = pygame.image.load(os.path.join("pics", "web_fullHD.png"))
circle = pygame.image.load(os.path.join("pics", "circle.png"))
player1_gex = pygame.image.load(os.path.join("pics", "player1_gex.png"))
player2_gex = pygame.image.load(os.path.join("pics", "player2_gex.png"))
soldier = pygame.image.load(os.path.join("pics", "soldier.png"))
horse = pygame.image.load(os.path.join("pics", "horse.png"))
green_gex = pygame.image.load(os.path.join("pics", "green_gex.png"))
tevton = pygame.image.load(os.path.join("pics", "tevton.png"))
turn_bttn = pygame.image.load(os.path.join("pics", "button.png"))
button_x1 = pygame.image.load(os.path.join("pics", "button1.png"))
button_x5 = pygame.image.load(os.path.join("pics", "button2.png"))
button_x10 = pygame.image.load(os.path.join("pics", "button3.png"))
green_down = pygame.image.load(os.path.join("pics", "green_down.png"))
green_down_left = pygame.image.load(os.path.join("pics", "green_down_left.png"))
green_down_right = pygame.image.load(os.path.join("pics", "green_down_right.png"))
green_up = pygame.image.load(os.path.join("pics", "green_up.png"))
green_up_left = pygame.image.load(os.path.join("pics", "green_up_left.png"))
green_up_right = pygame.image.load(os.path.join("pics", "green_up_right.png"))
red_down = pygame.image.load(os.path.join("pics", "red_down.png"))
red_down_left = pygame.image.load(os.path.join("pics", "red_down_left.png"))
red_down_right = pygame.image.load(os.path.join("pics", "red_down_right.png"))
red_up = pygame.image.load(os.path.join("pics", "red_up.png"))
red_up_left = pygame.image.load(os.path.join("pics", "red_up_left.png"))
red_up_right = pygame.image.load(os.path.join("pics", "red_up_right.png"))
